"""1_location

Revision ID: 26c8f9bcd160
Revises: 10cac43cb440
Create Date: 2024-11-17 12:02:32.870023

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.contrib.location import PlaceLevelChoices
from app.conf import LanguagesChoices

# revision identifiers, used by Alembic.
revision = '26c8f9bcd160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'place',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('location_level', sqlalchemy_utils.types.choice.ChoiceType(
            choices=PlaceLevelChoices, impl=sa.String(8)
        ), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('tree_id', sa.Integer(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('lft', sa.Integer(), nullable=False),
        sa.Column('rgt', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['place.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_level'), 'place', ['level'], unique=False)
    op.create_index(op.f('ix_place_lft'), 'place', ['lft'], unique=False)
    op.create_index(op.f('ix_place_rgt'), 'place', ['rgt'], unique=False)
    op.create_index(op.f('ix_place_slug'), 'place', ['slug'], unique=True)
    op.create_table(
        'place_tr',
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('locale', sqlalchemy_utils.types.choice.ChoiceType(
            choices=LanguagesChoices, impl=sa.String(length=10)
        ), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['place.id'], name='fx_place_tr_place_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'locale'),
        sa.UniqueConstraint('id', 'locale', name='ux_place_tr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_tr')
    op.drop_index(op.f('ix_place_slug'), table_name='place')
    op.drop_index(op.f('ix_place_rgt'), table_name='place')
    op.drop_index(op.f('ix_place_lft'), table_name='place')
    op.drop_index(op.f('ix_place_level'), table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
