"""3_user_address

Revision ID: 3b83acdcc82e
Revises: 10cac43cb440
Create Date: 2024-11-17 13:15:44.632268

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b83acdcc82e'
down_revision = '10cac43cb440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_address',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('place_id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('customer_name', sa.String(length=255), nullable=False),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['place_id'], ['place.id'], name='fx_u_address_place_id',
                                ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fx_u_address_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    # ### end Alembic commands ###
