"""3_file

Revision ID: 4181410cc861
Revises: b91096c2229f
Create Date: 2024-11-20 10:16:13.342621

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.contrib.file import FileTypeChoices, ContentTypeChoices, ThumbnailCropChoices

# revision identifiers, used by Alembic.
revision = '4181410cc861'
down_revision = '514372b0c547'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_type', sqlalchemy_utils.types.choice.ChoiceType(
        choices=FileTypeChoices, impl=sa.String(length=25)
    ), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_host', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content_type', sqlalchemy_utils.types.choice.ChoiceType(
        choices=ContentTypeChoices, impl=sa.String(length=50)
    ), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('poster', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thumbnail',
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('crop', sqlalchemy_utils.types.choice.ChoiceType(
        choices=ThumbnailCropChoices, impl=sa.String(length=25)
    ), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnail')
    op.drop_table('file')
    # ### end Alembic commands ###
