"""7_user_session_extra_fields

Revision ID: 424df58948dc
Revises: 3d0bf138b5df
Create Date: 2024-12-01 16:22:50.515295

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '424df58948dc'
down_revision = '3d0bf138b5df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_session', sa.Column('firebase_device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session', 'firebase_device_id')
    op.drop_column('user_session', 'expire_at')
    # ### end Alembic commands ###
