"""2_config

Revision ID: 514372b0c547
Revises: 26c8f9bcd160
Create Date: 2024-11-20 06:19:36.034379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from app.conf import LanguagesChoices
# revision identifiers, used by Alembic.
revision = '514372b0c547'
down_revision = '26c8f9bcd160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('support_phone', sa.String(length=255), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('phones', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('emails', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('regular_shipping_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('express_shipping_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_tr',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.String(length=255), nullable=False),
    sa.Column('seo_keywords', sa.String(length=500), nullable=False),
    sa.Column('locale', sqlalchemy_utils.types.choice.ChoiceType(
        choices=LanguagesChoices, impl=sa.String(10)
    ), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['config.id'], name='fx_config_config_tr_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale'),
    sa.UniqueConstraint('id', 'locale', name='ux_config_tr_id_locale'),
    sa.UniqueConstraint('locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_tr')
    op.drop_table('config')
    # ### end Alembic commands ###
