"""8_policy

Revision ID: a0aa6e7d6021
Revises: 424df58948dc
Create Date: 2024-12-02 08:16:45.503081

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.conf import LanguagesChoices

# revision identifiers, used by Alembic.
revision = 'a0aa6e7d6021'
down_revision = '424df58948dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'policy_tr',
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('locale', sqlalchemy_utils.types.choice.ChoiceType(
            choices=LanguagesChoices, impl=sa.String(length=10)
        ), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('locale', 'id'),
        sa.UniqueConstraint('locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_tr')
    # ### end Alembic commands ###
