"""9_slider

Revision ID: cc62af102737
Revises: a0aa6e7d6021
Create Date: 2024-12-03 18:32:22.438705

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.conf import LanguagesChoices
# revision identifiers, used by Alembic.
revision = 'cc62af102737'
down_revision = 'a0aa6e7d6021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'slider',
        sa.Column('host', sa.String(length=255), nullable=True),
        sa.Column('path', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='fx_slider_file_id', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id')
    )
    op.create_table(
        'slider_tr',
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('caption', sa.String(length=255), nullable=False),
        sa.Column('locale', sqlalchemy_utils.types.choice.ChoiceType(
            choices=LanguagesChoices, impl=sa.String(length=10)
        ), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['slider.id'], name='fx_slider_slider_tr_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'locale'),
        sa.UniqueConstraint('id', 'locale', name='ux_slider_tr_id_locale'),
        sa.UniqueConstraint('locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_tr')
    op.drop_table('slider')
    # ### end Alembic commands ###
